kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-example-spartan-pvc
  namespace: app-example-spartan
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi