apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-gold-armadillo-12
  namespace: default
spec:
  dataVolumeTemplates:
    - metadata:
        name: fedora-gold-armadillo-12-volume
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: '32212254720'
          storageClassName: gp3-csi
  instancetype:
    name: u1.2xmedium
  preference:
    name: fedora
  runStrategy: Always
  template:
    metadata:
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        devices:
          autoattachPodInterface: false
          disks: []
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: fedora-gold-armadillo-12-volume
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: bicc-rb4u-xpgj
              user: fedora
          name: cloudinitdisk
