apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: application-menu-spartan-github
spec:
  href: 'https://github.com/NotAMorningSpartan'
  location: ApplicationMenu
  text: GitHub
  applicationMenu:
    section: Internal Links
    imageURL: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
