apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-app-example-spartan
  namespace: openshift-gitops
spec:
  destination:
    namespace: app-example-spartan
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/NotAMorningSpartan/openshift-gitops-getting-started.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true