apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
type: Opaque
data:
  htpasswd: dXNlcjE6JDJ5JDA1JHovdlVxY3l2QTcyYUZSYmJGYjVyaGVhaFV3d28uNFVZT1p6eUN5amFnQVhoem1nb3puV3lPCnVzZXIyOiQyeSQwNSRjT2VaLkVyM3YuUjBlZ091MS9ramR1bEI5MjI0bFVkL3hNdTNobm1ZaE53SG43Q0VTUXM0Mg==